name: Erotica
favicon: null
layout_spectrum: 0.85514
typography_spectrum: 0.3822
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#2c2c2c'
    - '#b8b8b8'
    - '#f9f9f9'
    - '#696969'
  brandStrength: 0.25
  lightness: 0.10993142169900239
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
